# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4425cd2398c8fafbff2ee2615d34ba003f0068a2165196e18b9089e03081cdda84bae40aff213a355a22fc050daae979c92e92937c121feee929a16660d7e0f

test:
  secret_key_base: 91f125d4e57e86f4e480ffdd002ebea91dd3b5d0d42d4837820527a4cb650ccefd2c125ea8ed902768ae12a1568fde3071a6c9dfe9ed2e509beb8f7db8a353be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
